services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    env_file:
      - ./db/mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:16
    container_name: postgres-db
    env_file:
      - ./db/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql_base/data

volumes:
  mysql_data:
  postgres_data: